version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_vehicle
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nodejs_app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: db_vehicle
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  mysql_data:
